test: allow empty $DB_ADDR for most tests
In vars.go we were doing some string validation at init time on the $DB_ADDR
variable, and panicking if it was unset or invalid. This meant that running
unittests panicked for those tests that depended on `vars`, even if they didn't
actually do any DB work. For instance:

    go test ./policy

Fix this by removing the init-time validation and inserting a placeholder string
if DB_ADDR is empty. This results in most tests passing without $DB_ADDR set.
For those tests that do rely on $DB_ADDR, we get an error message like this:

    go test ./sa
    ...
    --- FAIL: TestSerialsForIncident (0.00s)
    sa_test.go:2924: Failed to create dbMap: dial tcp: lookup unset DB_ADDR: no such host