mtca/publisher: make MirrorID nullable (#8968)
This field is null when a checkpoint is first created. Represent it as a
`*string`. This fixes a unittest error I was seeing locally:

```
--- FAIL: TestPublish (0.01s)
    mtpublisher_test.go:190: p.Publish(): selecting the latest checkpoint: failed to select one *mtpublisher.checkpointEntry (unknown table): sql: Scan error on column index 3, name "mirrorID": converting NULL to string is unsupported
```