Revert "integration: move to Python3 (#4313)" (#4323)
This reverts commit 796a7aa2f46e53199c8772382eab49998fb405a9.

People's tests have been breaking on `docker-compose up` with the following output:

```
ImportError: No module named requests
```

Fixes #4322