sa: return corepb.Empty{} not nil.
The new `RevokeAuthorizationsByDomain2` and `DeactivateAuthorization2`
SA RPCs are declared to return `*corepb.Empty, error` but were
implemented to `return nil, nil` for the success case. This causes
a gRPC unmarshal error:

```
E151233 boulder-sa [AUDIT] grpc: server failed to encode response:  rpc
error: code = Internal desc = grpc: error while marshaling: proto:
Marshal called with nil
```

Both RPCs should `return &corepb.Empty{}, nil` to avoid this.