CI/Dev: restore allowOrigins wfe/wfe2 config. (#4650)
In 67ec373a96856036d870580d4c5c367f23b44242 we removed "unused" WFE and WFE2
config elements. Unfortunately I missed that one of these elements,
`allowOrigins`, **is** used and without this config in
place CORS is broken.

We have unit tests for the CORS headers but we did not have any end-to-end
integration tests that would catch a problem with the WFE/WFE2 missing the
`allowOrigins` config element.

This commit restores the `allowOrigins` config value across the WFE/WFE2
configs and also adds a very small integration test. That test only checks one
CORS header and only for the HTTP ACMEv2 endpoint but I think it's sufficient
for the moment (and definitely better than nothing).

Prior to fixing the config elements the integration test fails as expected:
```
--- FAIL: TestWFECORS (0.00s)
    wfe_test.go:28: "" != "*"
FAIL
FAIL	github.com/letsencrypt/boulder/test/integration	0.014s
FAIL
```