Improve output when Go integration tests fail.
Right now we show output like:

Traceback (most recent call last):
  File "test/integration-test.py", line 60, in run_go_tests
    subprocess.check_call(cmdLine, shell=False, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'test', '-tags', 'integration', '-count=1', '-race', './test/integration']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test/integration-test.py", line 414, in <module>
    main()
  File "test/integration-test.py", line 293, in main
    run_go_tests(args.test_case_filter)
  File "test/integration-test.py", line 62, in run_go_tests
    raise(Exception("%s. Output:\n%s" % (e, e.output)))
Exception: Command '['go', 'test', '-tags', 'integration', '-count=1', '-race', './test/integration']' returned non-zero exit status 1. Output:
None

This change removes the try / raise clauses that were causing this
double exception handling. The original purpose of these clauses was to
make sure we logged output on failure. To continue to fulfill that
purpose, I switched the `run` function to use check_call instead of
check_output. check_output captures the stdout; check_call emits it to
the caller's stdout as normal, so we still see the output.

I also changed the two cases that actually wanted to process output so
they use check_output directly.