Integrate zlint into cert-checker.
Also remove doNotForceCN from configs, since that flag will not be enabled (and
it breaks linting).

Note: two tests in dependencies currently fail. I've filed a PR for one
and an issue for the other. We should probably hold off on merging until
those are resolved (though the URL parsing one doesn't affect us).

```
$ go test github.com/asaskevich/govalidator github.com/zmap/zcrypto/{json,x509} github.com/zmap/zlint/{,util,lints}
--- FAIL: TestIsRequestURI (0.00s)
        validator_test.go:870: Expected IsRequestURI("irc://#channel@network") to be true, got false
--- FAIL: TestIsRequestURL (0.00s)
        validator_test.go:821: Expected IsRequestURL("irc://#channel@network") to be true, got false
FAIL
FAIL    github.com/asaskevich/govalidator       0.020s
ok      github.com/zmap/zcrypto/json    0.017s
ok      github.com/zmap/zcrypto/x509    2.323s
ok      github.com/zmap/zlint   0.228s
ok      github.com/zmap/zlint/util      0.023s
asn1: structure error: explicitly tagged member didn't match
--- FAIL: TestSANEDIPartyMissing (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x530 pc=0x6a24d5]

goroutine 252 [running]:
testing.tRunner.func1(0xc42041f680)
        /home/jsha/go1.10/src/testing/testing.go:742 +0x29d
panic(0x76d1e0, 0xa73cb0)
        /home/jsha/go1.10/src/runtime/panic.go:505 +0x229
github.com/zmap/zlint/util.IsServerAuthCert(0x0, 0x785ac0)
        /home/jsha/gopkg/src/github.com/zmap/zlint/util/ca.go:48 +0x5
github.com/zmap/zlint/lints.(*Lint).Execute(0xc4202dd500, 0x0, 0x80606d)
        /home/jsha/gopkg/src/github.com/zmap/zlint/lints/base.go:103 +0x117
github.com/zmap/zlint/lints.TestSANEDIPartyMissing(0xc42041f680)
        /home/jsha/gopkg/src/github.com/zmap/zlint/lints/lint_ext_san_edi_party_name_present_test.go:33 +0x9e
testing.tRunner(0xc42041f680, 0x81e720)
        /home/jsha/go1.10/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
        /home/jsha/go1.10/src/testing/testing.go:824 +0x2e0
FAIL    github.com/zmap/zlint/lints     0.075s
```